### ISSUE TITLE
Add A High Score on the Game

### ISSUE THREAD

**Issue by TheSpeedX** [TheSpeedX/NoisyBird#1]
A Simple Feature where we need to show the high score of each game session at the top

When a user replays the game after it's he should be able to see his high score basically

**Comment by JasonT1085** [comment]
Hi! I would like to work on this issue!

**Comment by TheSpeedX** [comment]
Yeah, sure you can go ahead.

**Comment by TheSpeedX** [comment]
Fixed By #7
